language: cpp

sudo: false

matrix:
  include:
  - os: linux
    compiler: gcc
    env: 
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - gcc++-4.9
  - os: linux
    compiler: clang
    env: 
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
          - clang++
  - os: linux
    compiler: gcc
    env: STATIC=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - gcc++-4.9
  - os: linux
    compiler: clang
    env: STATIC=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
          - clang++

branches:
  except:
    - gh-pages

install:
  - ./autogen.sh
  - ./configure ${STATIC+--disable-shared} ${DEBUG+--enable-debug} ${VALGRIND+--enable-valgrind} ${CENSUS+--enable-census} ${NOTHREADS+--disable-threads} CFLAGS="-O3 ${POLL+-DDILL_POLL} ${ARCH_FALLBACK+-DDILL_ARCH_FALLBACK} ${THREAD_FALLBACK+-DDILL_THREAD_FALLBACK}"
  - make V=1 ${DIST+dist}

script:
  - test ${DIST+x} || make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
